load("//.bazelbsp/common:common.bzl", "intellij_common")
load("//.bazelbsp/common:dependencies.bzl", "intellij_deps")
load("//.bazelbsp/common:ide_info.bzl", "ide_info")
load("//.bazelbsp/modules:provider.bzl", "intellij_provider")
load("//.bazelbsp/modules:run_info.bzl", "intellij_run_info_aspect")
load("//.bazelbsp/modules:test_info.bzl", "intellij_test_info_aspect")
load(":provider.bzl", "IntelliJInfo", "intellij_info_builder")
# Copyright 2025 The Bazel Authors.
# Copyright 2026 JetBrains s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Derived from: https://github.com/bazelbuild/intellij/blob/5ec21e640ed59b316b58559d8e79cb0858e519bd/aspect/intellij_info_impl.bzl


# compile time dependencies collected for every target
COMPILE_TIME_DEPS = ["deps"]

# Rule kinds to include in outputs, even though no special information is available
EXTRA_RULES = ["sh_binary", "sh_library", "genrule", "intellij_plugin_debug_target", "_plugin_deploy_zip", "intellij_plugin_zip"]

def _merge_dependencies(builder, ctx):
    """Adds information from all dependencies' intellij info providers."""
    for name in dir(ctx.rule.attr):
        for dep in intellij_common.attr_as_label_list(ctx, name):
            if not IntelliJInfo in dep:
                continue

            intellij_info_builder.append(builder, dep[IntelliJInfo])

def _serialize_dependencies(builder):
    """Serializes all dependencies currently tracked by the builder."""
    return depset([
        struct(target = dep[intellij_common.TargetInfo].partial_key, dependency_type = key)
        for key, list_of_sets in builder.dependencies.items()
        for set in list_of_sets
        for dep in set.to_list()
        if intellij_common.TargetInfo in dep
    ]).to_list()

def _collect_toolchain_info(target):
    return [
        target[provider]
        for provider in intellij_provider.TOOLCHAINS
        if provider in target and target[provider].present
    ]

def _merge_target_info(builder, target, ctx):
    """Adds information collected from the current target's module providers."""

    if AnalysisTestResultInfo in target:
        # We are not allowed to create an action (including a file-write action) for a target
        # defined by an analysis-test rule.
        return

    # for backwards compatibility with Bazel 8 and below, toolchains are dependencies
    intellij_info_builder.append_ide_infos(builder, [it.info_file for it in _collect_toolchain_info(target)])

    # do not generate a intellij-info.txt if there is no language module attached
    if (not intellij_provider.has_module(target)) and (not ctx.rule.kind in EXTRA_RULES):
        return

    info = {}

    # iterate over all providers that could be generated by a module aspect
    for name, module_provider in intellij_provider.MODULE_MAP.items():
        if not module_provider in target or not target[module_provider].present:
            continue

        provider = target[module_provider]

        # update the data persisted to the output file
        info[name] = provider.value

        # merge all information provided by the module provider into the main provider
        intellij_info_builder.append(builder, provider)

        toolchain_infos = [
            info
            for toolchain_target in provider.toolchains
            for info in _collect_toolchain_info(toolchain_target)
        ]

        # add toolchains as dependencies to the current target
        intellij_info_builder.append_dependencies(
            builder,
            intellij_deps.TOOLCHAIN,
            depset([it.owner for it in toolchain_infos]),
        )

        # append the already generated info from the toolchains
        intellij_info_builder.append_ide_infos(builder, [it.info_file for it in toolchain_infos])

    info["deps"] = _serialize_dependencies(builder)

    # generate the target key based on the information currently accumulated by the builder
    key = intellij_info_builder.build_target_key(builder, target, ctx)

    # Materialize generated sources
    intellij_info_builder.append_output(
        builder,
        intellij_provider.BUILD_OUTPUT,
        [
            f
            for target in intellij_common.attr_as_label_list(ctx, "srcs")
            for f in (target[DefaultInfo].files or depset()).to_list()
            if not f.is_source
        ],
    )

    # dependencies have to be serialized last because they might be updated by module providers
    # write the ide info to file and add the generated file to the appropriate output group
    intellij_info_builder.append_ide_infos(builder, [ide_info.write(target, ctx, key, info)])

def _aspect_impl(target, ctx):
    builder = intellij_info_builder.create()

    intellij_info_builder.append_dependencies(
        builder,
        intellij_deps.COMPILE_TIME,
        intellij_deps.collect(ctx, COMPILE_TIME_DEPS),
    )

    _merge_target_info(builder, target, ctx)
    _merge_dependencies(builder, ctx)

    intellij_info = intellij_info_builder.build(builder, target, ctx)

    return [intellij_info, OutputGroupInfo(**intellij_info.outputs)]

intellij_info_aspect = intellij_common.aspect(
    implementation = _aspect_impl,
    requires = [intellij_test_info_aspect, intellij_run_info_aspect],
    required_aspect_providers = [[it] for it in intellij_provider.ALL],
    provides = [IntelliJInfo],
)